version: "3.1"
services:

  traefik: #service de routing inversé 
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db: 
    image: mariadb:10.3
    container_name: dbauth #Le nom de conteneur
    restart: always 
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbroot#livrairie#ADONIS6 
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

  frontend:
    image: ghcr.io/kylian2/livrairie:main-front
    ports:
    - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`kylianrichard.site`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend2.rule=Host(`www.kylianrichard.site`)"
      - "traefik.http.routers.frontend2.entrypoints=web"

  backend:
    image: ghcr.io/kylian2/livrairie:main-back
    ports:
    - 3333:3333
    depends_on:
      - db

volumes:
  dbdata: 
