name : Docker Build and Publish

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Packages
    uses: docker/login-action@v1
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push front-end image
      id: build-and-push-front
      uses: docker/build-push-action@v3
      with:
        context: ./books-front
        file: ./books-front/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:front-latest
          ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:front-${{ github.event.commits[0].sha }}

    - name: Build and push back-end image
      id: build-and-push-back
      uses: docker/build-push-action@v3
      with:
        context: ./books
        file: ./books/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:back-latest
          ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:back-${{ github.event.commits[0].sha }}
